disableHugoGeneratorInject = true
preserveTaxonomyNames = true
PygmentsCodeFences = true
pygmentsstyle = "xcode"

theme = "hansott"
baseURL = "https://hansott.github.io"
languageCode = "en"
title = "Hans Ott"
GoogleAnalytics = "UA-42118181-2"
disqusShortname = "hansott"

[params]
    author = "Hans Ott"
    description = "I'm a web & mobile developer with a strong interest in domain-driven design and functional programming."
    email = "hansott@hotmail.be"
    githubUsername = "hansott"
    stackOverflowId = 3455472
    twitterUsername = "otthans"
    linkedInUsername = "otthans"

[taxonomies]
tag = "tags"

[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    name = "Reading list"
    url = "/reading-list/"

[[menu.main]]
    name = "Packages"
    url = "/packages/"
